# Generated by Django 3.0.8 on 2020-07-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='base_tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
            preserve_default=False,
        ),
    ]
